### ISSUE TITLE
interact timer progress - displayed on the item checklist

### ISSUE THREAD

**Issue by FlynnMay** [AIESydneyStudents/DIGITAL_BASKET#117]

**Comment by Oraxien40** [comment]
Hey Flynn I have a couple of notes on this.
- To start could you turn off the old radial progress bar
- Also when you are dropping off the item could it go in reverse
- And finally, could there be a delay between when the circle disappears and the tick appears (when they are implemented) I say this because currently we have the checkbox itself disappearing, and from my understanding that shouldn't happen at all.

**Comment by Oraxien40** [comment]
The first two of my previous points have been addressed and I have no further suggestions on those.
But the third point should be fine to ignore for now.
![Capture7](https://user-images.githubusercontent.com/82855401/142802792-f295f6e5-b3a2-4bdb-a156-b38016c60767.PNG)
